#!/usr/bin/env ruby
def macblame(file_name)
	contributor = {}
	output = open("| git blame "+file_name)
	feed = output.read()
	lines = feed.split("\n")
	commits = lines.length
	lines.each do |line|
		tokens = line.split("(")
		name = tokens[1].split(" ")[0]
		if contributor[name].nil?
			contributor[name] = 1
		else
			contributor[name] += 1
		end
	end
	sorted_hash = contributor.sort.sort do |a,b|
		b[1] <=> a[1]
	end
	print "for file #{file_name}.. \n"
	sorted_hash.each do |i|
		puts "Contributor: #{i[0]} with #{(i[1].to_f/commits.to_f)*100} % contribution with #{i[1]} lines of code"
	end
	puts "* "*25
end
def print_general_message
	print "macblame - A better alternative to 'git blame'\n\n"
	puts "Usage:"
	print "macblame <filename 1> <filename 2> ..... \n\n"
	puts "Description:"
	print "macblame shows stats about the files tracked by git. It uses the output of 'git blame' and summarize it in a cleaner and intuitive format."
	puts "\n\n Credits:"
	print "Prasanna Sundar  -  prassi  -  praserocking@gmail.com"
end

if ARGV.length == 0
	print_general_message
else
	ARGV.each do |name|
		macblame(name)
	end
end